language: rust
dist: bionic

cache: cargo
rust:
  - stable

addons:
    apt:
        packages:
            - libssl-dev

before_script: |
  cargo install cargo-tarpaulin

script:
  - cargo test --release

after_success: |
  cargo tarpaulin --timeout 10000 --out Xml
  bash < (curl -s https://codecov.io/bash)