[package]
name = "nessa"
version = "0.1.0"
authors = ["Gabie <jacadel1998@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
rand = "*"
impl_ops = "*"
rayon = "1.5"
bit-set = "*"
nom = "7"
clap = "*"

[dev-dependencies]
num-traits = "*"
num-bigint = { version = "0.4", features = ["rand"] }